import type { RecommendedMcpServer } from '../agent/mcp/registry.js';

export const MCP_SERVERS: RecommendedMcpServer[] = [
  {
    id: 'pikiloom-browser',
    name: 'Browser Automation',
    description: 'Optimized Playwright MCP — managed Chrome with shared profile, CDP attach, and supervisor lifecycle.',
    descriptionZh: '基于 Playwright MCP 的定制版浏览器自动化：受管 Chrome、共享 profile、CDP 附着、进程级 supervisor。',
    category: 'utility',
    recommendedScope: 'global',
    transport: { type: 'stdio', command: '@playwright/mcp', args: ['(managed by pikiloom)'] },
    auth: { type: 'none' },
    iconSlug: 'playwright',
    homepage: 'https://github.com/microsoft/playwright-mcp',
    isBuiltin: true,
  },
  {
    id: 'peekaboo',
    name: 'Peekaboo',
    description: 'Native macOS GUI control via Accessibility API + ScreenCaptureKit (click, type, scroll, windows, menus, Dock). Requires Screen Recording + Accessibility permissions. macOS only.',
    descriptionZh: '通过 macOS Accessibility 与 ScreenCaptureKit 实现原生 GUI 控制（点击、输入、滚动、窗口、菜单、Dock）。需要"屏幕录制"与"辅助功能"两项系统权限，仅支持 macOS。',
    category: 'utility',
    recommendedScope: 'global',
    transport: { type: 'stdio', command: 'npx', args: ['-y', '-p', '@steipete/peekaboo', 'peekaboo-mcp'] },
    auth: { type: 'none' },
    iconSlug: 'peekaboo',
    iconUrl: 'https://peekaboo.sh/favicon.svg',
    homepage: 'https://peekaboo.sh/',
    isBuiltin: true,
  },

  {
    id: 'filesystem',
    name: 'Filesystem',
    description: 'Read, write, and search files on the local machine',
    descriptionZh: '读写和搜索本机文件',
    category: 'utility',
    recommendedScope: 'workspace',
    transport: { type: 'stdio', command: 'npx', args: ['-y', '@modelcontextprotocol/server-filesystem', '${WORKDIR}'] },
    auth: { type: 'none' },
    iconSlug: 'filesystem',
  },
  {
    id: 'sqlite',
    name: 'SQLite',
    description: 'Query and manage local SQLite databases',
    descriptionZh: '查询和管理本地 SQLite 数据库',
    category: 'data',
    recommendedScope: 'workspace',
    transport: { type: 'stdio', command: 'uvx', args: ['mcp-server-sqlite', '--db-path', '${WORKDIR}/data.db'] },
    auth: { type: 'none' },
    iconSlug: 'sqlite',
  },
  {
    id: 'postgres',
    name: 'PostgreSQL',
    description: 'Query and manage PostgreSQL databases',
    descriptionZh: '查询和管理 PostgreSQL 数据库',
    category: 'data',
    recommendedScope: 'workspace',
    transport: { type: 'stdio', command: 'npx', args: ['-y', '@modelcontextprotocol/server-postgres', '${POSTGRES_CONNECTION_STRING}'] },
    auth: {
      type: 'credentials',
      fields: [{
        key: 'POSTGRES_CONNECTION_STRING',
        label: 'Connection string',
        labelZh: '连接串',
        required: true,
        placeholder: 'postgresql://user:pass@host:5432/db',
      }],
    },
    iconSlug: 'postgres',
  },

  {
    id: 'github',
    name: 'GitHub',
    description: 'Repositories, pull requests, issues, code search',
    descriptionZh: '仓库、PR、Issue、代码搜索',
    category: 'dev',
    recommendedScope: 'global',
    transport: { type: 'http', url: 'https://api.githubcopilot.com/mcp/' },
    auth: { type: 'mcp-oauth', scopes: ['repo', 'read:org'] },
    iconSlug: 'github',
    homepage: 'https://github.com/github/github-mcp-server',
  },
  {
    id: 'atlassian',
    name: 'Atlassian',
    description: 'Jira issues, Confluence pages, sprint planning',
    descriptionZh: 'Jira 工单、Confluence 文档、Sprint 管理',
    category: 'productivity',
    recommendedScope: 'global',
    transport: { type: 'http', url: 'https://mcp.atlassian.com/v1/sse' },
    auth: { type: 'mcp-oauth' },
    iconSlug: 'atlassian',
    homepage: 'https://www.atlassian.com/platform/remote-mcp-server',
  },
  {
    id: 'notion',
    name: 'Notion',
    description: 'Read, write, and search Notion pages and databases',
    descriptionZh: '读写和搜索 Notion 页面与数据库',
    category: 'productivity',
    recommendedScope: 'global',
    transport: { type: 'http', url: 'https://mcp.notion.com/mcp' },
    auth: { type: 'mcp-oauth' },
    iconSlug: 'notion',
    homepage: 'https://developers.notion.com/docs/mcp',
  },
  {
    id: 'linear',
    name: 'Linear',
    description: 'Issues, projects, cycles, and team workflows',
    descriptionZh: 'Issue、项目、周期和团队协作',
    category: 'productivity',
    recommendedScope: 'global',
    transport: { type: 'http', url: 'https://mcp.linear.app/sse' },
    auth: { type: 'mcp-oauth' },
    iconSlug: 'linear',
    homepage: 'https://linear.app/docs/mcp',
  },
  {
    id: 'sentry',
    name: 'Sentry',
    description: 'Error tracking — search issues, view stack traces',
    descriptionZh: '错误追踪 — 查询 Issue、查看堆栈',
    category: 'dev',
    recommendedScope: 'global',
    transport: { type: 'http', url: 'https://mcp.sentry.dev/mcp' },
    auth: { type: 'mcp-oauth' },
    iconSlug: 'sentry',
    homepage: 'https://docs.sentry.io/product/sentry-mcp/',
  },

  {
    id: 'cloudflare-bindings',
    name: 'Cloudflare',
    description: 'Manage Workers, Pages, R2, D1, KV — the full control plane',
    descriptionZh: '管理 Workers / Pages / R2 / D1 / KV — 完整控制面',
    category: 'dev',
    recommendedScope: 'global',
    transport: { type: 'http', url: 'https://bindings.mcp.cloudflare.com/sse' },
    auth: { type: 'mcp-oauth' },
    iconSlug: 'cloudflare',
    homepage: 'https://developers.cloudflare.com/agents/model-context-protocol/',
  },
  {
    id: 'cloudflare-observability',
    name: 'Cloudflare Observability',
    description: 'Workers logs, analytics, and traces',
    descriptionZh: 'Workers 日志、分析与追踪',
    category: 'dev',
    recommendedScope: 'global',
    transport: { type: 'http', url: 'https://observability.mcp.cloudflare.com/sse' },
    auth: { type: 'mcp-oauth' },
    iconSlug: 'cloudflare',
    homepage: 'https://developers.cloudflare.com/agents/model-context-protocol/',
  },
  {
    id: 'cloudflare-docs',
    name: 'Cloudflare Docs',
    description: 'Search and query Cloudflare documentation',
    descriptionZh: '搜索和查询 Cloudflare 文档',
    category: 'dev',
    recommendedScope: 'global',
    transport: { type: 'http', url: 'https://docs.mcp.cloudflare.com/sse' },
    auth: { type: 'mcp-oauth' },
    iconSlug: 'cloudflare',
    homepage: 'https://developers.cloudflare.com/agents/model-context-protocol/',
  },

  {
    id: 'gamma',
    name: 'Gamma',
    description: 'Generate AI-powered presentations and documents',
    descriptionZh: '生成 AI 驱动的演示文稿和文档',
    category: 'productivity',
    recommendedScope: 'global',
    transport: { type: 'http', url: 'https://mcp.gamma.app/mcp' },
    auth: { type: 'mcp-oauth' },
    iconSlug: 'gamma',
    homepage: 'https://gamma.app/docs/mcp',
  },
  {
    id: 'hugging-face',
    name: 'Hugging Face',
    description: 'Models, datasets, spaces, and inference',
    descriptionZh: '模型、数据集、Spaces 和推理',
    category: 'dev',
    recommendedScope: 'global',
    transport: { type: 'http', url: 'https://huggingface.co/mcp' },
    auth: { type: 'mcp-oauth' },
    iconSlug: 'huggingface',
    homepage: 'https://huggingface.co/docs/hub/mcp',
  },
  {
    id: 'slack',
    name: 'Slack',
    description: 'Read channels, summarize threads, send messages',
    descriptionZh: '读取频道、总结对话、发送消息',
    category: 'communication',
    recommendedScope: 'global',
    transport: { type: 'http', url: 'https://slack.com/api/mcp' },
    auth: { type: 'mcp-oauth' },
    iconSlug: 'slack',
    homepage: 'https://api.slack.com/apis/mcp',
  },
  {
    id: 'lark',
    name: '飞书 / Lark',
    description: 'Feishu docs, messages, tasks, bitable',
    descriptionZh: '飞书文档、消息、任务、多维表格',
    category: 'communication',
    recommendedScope: 'global',
    transport: { type: 'http', url: 'https://open.feishu.cn/mcp' },
    auth: { type: 'mcp-oauth' },
    iconSlug: 'lark',
    homepage: 'https://open.feishu.cn/document/mcp',
  },
  {
    id: 'gmail',
    name: 'Gmail',
    description: 'Read, search, send, and manage Gmail messages, threads, and labels. One-time sign-in via `npx @gongrzhe/server-gmail-autoauth-mcp auth`.',
    descriptionZh: '读取、搜索、发送和管理 Gmail 邮件、会话与标签。首次需运行 `npx @gongrzhe/server-gmail-autoauth-mcp auth` 完成 Google 授权。',
    category: 'communication',
    recommendedScope: 'global',
    transport: { type: 'stdio', command: 'npx', args: ['-y', '@gongrzhe/server-gmail-autoauth-mcp'] },
    auth: { type: 'none' },
    iconSlug: 'gmail',
    homepage: 'https://github.com/GongRzhe/Gmail-MCP-Server',
  },
  {
    id: 'outlook',
    name: 'Outlook',
    description: 'Microsoft 365 / Outlook email via Microsoft Graph — read, search, send, and organize mail. One-time device-code sign-in via `npx @softeria/ms-365-mcp-server --login`.',
    descriptionZh: '通过 Microsoft Graph 访问 Microsoft 365 / Outlook 邮箱 — 读取、搜索、发送和整理邮件。首次需运行 `npx @softeria/ms-365-mcp-server --login` 完成设备码登录。',
    category: 'communication',
    recommendedScope: 'global',
    transport: { type: 'stdio', command: 'npx', args: ['-y', '@softeria/ms-365-mcp-server', '--preset', 'mail'] },
    auth: { type: 'none' },
    iconSlug: 'outlook',
    homepage: 'https://github.com/softeria/ms-365-mcp-server',
  },

  {
    id: 'stripe',
    name: 'Stripe',
    description: 'Payments, customers, subscriptions, invoices',
    descriptionZh: '支付、客户、订阅、账单',
    category: 'data',
    recommendedScope: 'global',
    transport: { type: 'http', url: 'https://mcp.stripe.com/v1/mcp' },
    auth: {
      type: 'credentials',
      fields: [{
        key: 'STRIPE_API_KEY',
        label: 'Secret key',
        labelZh: 'Secret key',
        secret: true,
        required: true,
        placeholder: 'sk_live_... or sk_test_...',
        helpUrl: 'https://dashboard.stripe.com/apikeys',
      }],
    },
    iconSlug: 'stripe',
    homepage: 'https://docs.stripe.com/mcp',
  },
  {
    id: 'brave-search',
    name: 'Brave Search',
    description: 'Web and local search via Brave Search API',
    descriptionZh: '通过 Brave Search API 进行网页搜索',
    category: 'search',
    recommendedScope: 'global',
    transport: { type: 'stdio', command: 'npx', args: ['-y', '@modelcontextprotocol/server-brave-search'] },
    auth: {
      type: 'credentials',
      fields: [{
        key: 'BRAVE_API_KEY',
        label: 'API key',
        labelZh: 'API 密钥',
        secret: true,
        required: true,
        helpUrl: 'https://api.search.brave.com/app/keys',
      }],
    },
    iconSlug: 'brave',
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    description: 'Answer engine with real-time web search',
    descriptionZh: '带实时网页检索的问答引擎',
    category: 'search',
    recommendedScope: 'global',
    transport: { type: 'http', url: 'https://api.perplexity.ai/mcp' },
    auth: {
      type: 'credentials',
      fields: [{
        key: 'PERPLEXITY_API_KEY',
        label: 'API key',
        labelZh: 'API 密钥',
        secret: true,
        required: true,
        helpUrl: 'https://www.perplexity.ai/settings/api',
      }],
    },
    iconSlug: 'perplexity',
  },
  {
    id: 'you-com',
    name: 'You.com',
    description: 'Web search, URL reading, and cited research via the You.com MCP server',
    descriptionZh: '通过 You.com MCP 服务进行网页搜索、网页阅读与带引用的研究',
    category: 'search',
    recommendedScope: 'global',
    transport: { type: 'http', url: 'https://api.you.com/mcp' },
    auth: {
      type: 'credentials',
      fields: [{
        key: 'YDC_API_KEY',
        label: 'API key',
        labelZh: 'API 密钥',
        secret: true,
        required: true,
        helpUrl: 'https://you.com/platform/api-keys',
      }],
    },
    iconSlug: 'you',
    homepage: 'https://you.com/docs',
  },
];
